#My Properties File
#Thu Oct 01 10:27:52 GST 2026
Env=qa
Java\ Home=C\:\\Users\\abhil\\Downloads\\eclipse-jee-2025-12-R-win32-x86_64\\eclipse\\plugins\\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.10.v20260205-0638\\jre
Java\ Version=21.0.10
Operating\ System\ =Windows 11
Operating\ System\ Version=10.0
Project\ Name=Phoenix Test Automation Framework
